Airport.create(name: "Calgary - CA", code:"YYC")
Airport.create(name: "Sao Paulo Guarulhos - BR", code:"GRU")
Airport.create(name: "Sao Paulo Congonhas - BR", code:"CGO")
Airport.create(name:"Curitiba - BR", code:"CWB")
Airport.create(name:"Orlando - USA", code:"MCO")
